services:
  locust-master:
    build: .
    volumes:
      - ./:/mnt/locust
      - ./results:/results
    command: >
      -f /mnt/locust/${LOCUSTFILE:-locustfile.py} 
      --master  
      --host ${API_HOST}  
      --csv /results/raw_locust_data/${TEST_NAME}  
      --csv-full-history  
      --html /results/locust_reports/${TEST_NAME}.html  
      --users ${USERS:-1}  
      --spawn-rate ${SPAWN_RATE:-1}  
      --run-time ${RUN_TIME:-60s}
      --headless
    networks:
      - locust-network
    environment:
      - TEST_NAME=${TEST_NAME}
      - TEST_RESULTS_FILE_NAME=${TEST_RESULTS_FILE_NAME}
      - USER_CLASS=${USER_CLASS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} 

  locust-worker:
    build: .
    volumes:
      - ./:/mnt/locust
    command: >
      -f /mnt/locust/${LOCUSTFILE:-locustfile.py}  
      --worker   
      --master-host locust-master
    networks:
      - locust-network
    depends_on:
      - locust-master
    deploy:
      replicas: ${WORKERS:-1}
    environment:
      - TEST_NAME=${TEST_NAME}
      - TEST_RESULTS_FILE_NAME=${TEST_RESULTS_FILE_NAME}
      - USER_CLASS=${USER_CLASS}

networks:
  locust-network:
    driver: bridge